contact_link = "a[data-target='#exampleModal']"
contact_modal = "#exampleModal"
contact_modal_label = "#exampleModalLabel"
contact_email = "#recipient-email"
contact_name = "#recipient-name"
contact_message = "#message-text"
contact_send = "button:has-text('Send message')"
contact_close = "#exampleModal .btn-secondary"
