category_laptops  = "//a[normalize-space(text())='Laptops']"
next_button       = "//button[normalize-space(text())='Next']"
previous_button   = "//button[normalize-space(text())='Previous']"
carousel          = "#carouselExampleIndicators"
nav_home    = "//a[normalize-space(text())='Home']"
nav_contact = "//a[normalize-space(text())='Contact']"
nav_about   = "//a[normalize-space(text())='About us']"
nav_cart    = "//a[normalize-space(text())='Cart']"
nav_login   = "//a[normalize-space(text())='Log in']"
nav_signup  = "//a[normalize-space(text())='Sign up']"
products = "#tbodyid .card"
