category_laptops = "//a[text()='Laptops']"
category_phones = "//a[text()='Phones']"
category_monitors = "//a[text()='Monitors']"
products = "//div[@id='tbodyid']/div"
next_button = "//button[text()='Next']"
previous_button = "//button[text()='Previous']"
carousel = "//div[@id='carouselExampleIndicators']"
nav_home = "//div[@class='navbar-nav ml-auto']//a[text()='Home']"
nav_contact = "//div[@class='navbar-nav ml-auto']//a[text()='Contact']"
nav_about = "//div[@class='navbar-nav ml-auto']//a[text()='About us']"
nav_cart = "//div[@class='navbar-nav ml-auto']//a[text()='Cart']"
nav_login = "//div[@class='navbar-nav ml-auto']//a[text()='Log in']"
nav_signup = "//div[@class='navbar-nav ml-auto']//a[text()='Sign up']"
