product_link = "//a[text()='Samsung galaxy s6']"
add_to_cart_button = "//a[text()='Add to cart']"
cart_link = "//a[text()='Cart']"
place_order_button = "//button[text()='Place Order']"
order_modal = "//div[@id='orderModal']"
order_name = "//input[@id='name']"
order_country = "//input[@id='country']"
order_city = "//input[@id='city']"
order_credit_card = "//input[@id='card']"
order_month = "//input[@id='month']"
order_year = "//input[@id='year']"
purchase_button = "//button[text()='Purchase']"
confirmation_box = "//h2[text()='Thank you for your purchase!']"
confirmation_ok = "//button[text()='OK']"
