home_link        = "//a[normalize-space(text())='Home']"
phones_category  = "//a[normalize-space(text())='Phones']"
laptops_category = "//a[normalize-space(text())='Laptops']"
samsung_phone    = "//a[normalize-space(text())='Samsung galaxy s6']"
sony_laptop      = "//a[normalize-space(text())='Sony vaio i5']"
add_to_cart_button = "//a[normalize-space(text())='Add to cart']"
cart_link        = "#cartur"
cart_sony        = "//td[contains(text(),'Sony vaio i5')]"
cart_samsung     = "text=Samsung galaxy s6"
product_cell_template   = "//td[contains(text(),'{}')]"
remove_button_template  = "//td[contains(text(),'{}')]/following-sibling::td/a"
total            = "text=Total"
total_heading = "h2:has-text('Total')"
total_label   = "#totalm"
total_heading = "h2:has-text('Total')"
total_amount  = "h3"
